version: "3.8"
services:
  api:
    container_name: api
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/app
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/data/db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
volumes:
  db_data:
